"""
SQLAlchemy Database Models for LLM-EduAttackGraph

Tables:
- targets
- scans
- ports
- services
- fingerprints
- knowledge_documents
- knowledge_chunks
- retrievals
- analyses
- findings
- validations
- reports
- audit_events

FAISS index is stored separately from this relational database.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum as PyEnum
from typing import Optional, List

from sqlalchemy import (
    Column, String, Integer, Float, Boolean, DateTime, Text, JSON,
    ForeignKey, Enum, Index, UniqueConstraint
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

Base = declarative_base()


def generate_uuid() -> str:
    return str(uuid.uuid4())


# ==============================================================================
# Enums
# ==============================================================================

class ScanStatus(str, PyEnum):
    PENDING = "pending"
    RUNNING = "running"
    FINGERPRINTING = "fingerprinting"
    ANALYZING = "analyzing"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class PortState(str, PyEnum):
    OPEN = "open"
    CLOSED = "closed"
    FILTERED = "filtered"


class VulnerabilityCategory(str, PyEnum):
    """Six categories from the paper."""
    O1_RCE = "O1_RCE"                           # Remote Code/Command Execution
    O2_SQL_INJECTION = "O2_SQL_INJECTION"        # SQL Injection
    O3_WEAK_PASSWORD = "O3_WEAK_PASSWORD"        # Weak Password
    O4_UNAUTHORIZED = "O4_UNAUTHORIZED"          # Unauthorized Access
    O5_TOKEN_TAMPERING = "O5_TOKEN_TAMPERING"    # Token Tampering
    O6_INFO_DISCLOSURE = "O6_INFO_DISCLOSURE"    # Sensitive Information Disclosure
    UNKNOWN = "UNKNOWN"


class SeverityLevel(str, PyEnum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFORMATIONAL = "informational"


class FindingStatus(str, PyEnum):
    """
    Human-in-the-loop workflow states.
    LLM output starts as POTENTIAL, never auto-confirmed.
    """
    POTENTIAL = "potential"           # LLM inferred this — NOT confirmed
    PENDING_REVIEW = "pending_review" # Queued for human review
    VALIDATED = "validated"           # Human accepted as a real finding
    REJECTED = "rejected"             # Human rejected (false positive)
    NEEDS_MORE_EVIDENCE = "needs_more_evidence"  # Human needs more info


class EvidenceType(str, PyEnum):
    """
    Evidence classification — critical for transparency.
    """
    OBSERVED = "observed"     # Directly obtained from reconnaissance
    RETRIEVED = "retrieved"   # From RAG knowledge base (Awesome-POC)
    INFERRED = "inferred"     # Generated by LLM (not confirmed)
    VALIDATED = "validated"   # Accepted by human analyst


# ==============================================================================
# Models
# ==============================================================================

class Target(Base):
    """
    Authorized target registry.
    Only targets registered here can be scanned.
    """
    __tablename__ = "targets"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    hostname = Column(String(255), nullable=False, index=True)
    ip_address = Column(String(45), nullable=True)  # IPv4 or IPv6
    description = Column(Text, nullable=True)
    authorized = Column(Boolean, default=True, nullable=False)
    authorization_note = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    scans = relationship("Scan", back_populates="target", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<Target hostname={self.hostname} authorized={self.authorized}>"


class Scan(Base):
    """
    Represents one complete scan session: fingerprint → RAG → LLM → validation.
    """
    __tablename__ = "scans"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    target_id = Column(String(36), ForeignKey("targets.id"), nullable=False)
    status = Column(Enum(ScanStatus), default=ScanStatus.PENDING, nullable=False, index=True)
    initiated_by = Column(String(255), nullable=True)  # user/system identifier
    notes = Column(Text, nullable=True)

    # Timing
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    started_at = Column(DateTime(timezone=True), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)

    # Configuration snapshot (at time of scan)
    embedding_model = Column(String(255), nullable=True)
    embedding_model_version = Column(String(100), nullable=True)
    faiss_index_version = Column(String(100), nullable=True)
    similarity_threshold = Column(Float, nullable=True)
    top_k = Column(Integer, nullable=True)
    llm_provider = Column(String(100), nullable=True)
    llm_model = Column(String(255), nullable=True)
    prompt_version = Column(String(50), nullable=True)

    error_message = Column(Text, nullable=True)

    # Relationships
    target = relationship("Target", back_populates="scans")
    ports = relationship("Port", back_populates="scan", cascade="all, delete-orphan")
    fingerprint = relationship("Fingerprint", back_populates="scan", uselist=False, cascade="all, delete-orphan")
    retrievals = relationship("Retrieval", back_populates="scan", cascade="all, delete-orphan")
    analyses = relationship("Analysis", back_populates="scan", cascade="all, delete-orphan")
    findings = relationship("Finding", back_populates="scan", cascade="all, delete-orphan")
    reports = relationship("Report", back_populates="scan", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<Scan id={self.id} status={self.status}>"


class Port(Base):
    """Open port discovered during fingerprinting."""
    __tablename__ = "ports"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    scan_id = Column(String(36), ForeignKey("scans.id"), nullable=False)
    port_number = Column(Integer, nullable=False)
    protocol = Column(String(10), default="tcp")
    state = Column(Enum(PortState), default=PortState.OPEN)
    evidence_type = Column(Enum(EvidenceType), default=EvidenceType.OBSERVED)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    scan = relationship("Scan", back_populates="ports")
    service = relationship("Service", back_populates="port", uselist=False, cascade="all, delete-orphan")

    __table_args__ = (
        Index("ix_ports_scan_port", "scan_id", "port_number"),
    )


class Service(Base):
    """Service identified on an open port."""
    __tablename__ = "services"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    port_id = Column(String(36), ForeignKey("ports.id"), nullable=False)
    name = Column(String(100), nullable=True)      # http, https, ftp, ssh, mysql, etc.
    version = Column(String(255), nullable=True)   # Apache/2.4.41, nginx/1.18.0
    product = Column(String(255), nullable=True)
    banner = Column(Text, nullable=True)
    evidence = Column(JSON, nullable=True)          # Raw detection evidence
    evidence_type = Column(Enum(EvidenceType), default=EvidenceType.OBSERVED)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    port = relationship("Port", back_populates="service")


class Fingerprint(Base):
    """
    Structured fingerprint produced by the fingerprinting engine.
    This is the output of Stage 1 (Algorithm 1 in the paper).
    The fingerprint text representation becomes the query for Stage 2 RAG.
    """
    __tablename__ = "fingerprints"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    scan_id = Column(String(36), ForeignKey("scans.id"), nullable=False, unique=True)

    # Raw structured data
    target_hostname = Column(String(255), nullable=False)
    raw_data = Column(JSON, nullable=False)         # Full fingerprint JSON

    # Extracted fields (from Algorithm 1 service_map)
    web_framework = Column(String(255), nullable=True)      # RuoYi, Spring, Django, etc.
    web_application = Column(String(255), nullable=True)
    server_software = Column(String(255), nullable=True)    # Apache, nginx, IIS
    server_version = Column(String(100), nullable=True)
    technologies = Column(JSON, nullable=True)              # List of detected technologies
    cms = Column(String(255), nullable=True)

    # Text representation (fed to embedding model as the query)
    text_representation = Column(Text, nullable=True)

    # Spark API pre-analysis (optional, from Algorithm 1)
    spark_analysis = Column(JSON, nullable=True)

    evidence_type = Column(Enum(EvidenceType), default=EvidenceType.OBSERVED)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    scan = relationship("Scan", back_populates="fingerprint")
    retrievals = relationship("Retrieval", back_populates="fingerprint", cascade="all, delete-orphan")


# ==============================================================================
# Knowledge Base
# ==============================================================================

class KnowledgeDocument(Base):
    """
    A vulnerability document ingested from Awesome-POC or other source.
    Paper: "Awesome-POC provides abundant vulnerability example data."
    """
    __tablename__ = "knowledge_documents"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    source = Column(String(100), nullable=False)           # awesome-poc, nvd, custom
    source_path = Column(String(500), nullable=True)       # File path in repo
    title = Column(String(500), nullable=True)
    category = Column(Enum(VulnerabilityCategory), default=VulnerabilityCategory.UNKNOWN)
    technology = Column(String(255), nullable=True)        # Spring, Log4j, Struts2
    framework = Column(String(255), nullable=True)
    version_affected = Column(String(255), nullable=True)
    description = Column(Text, nullable=True)
    remediation = Column(Text, nullable=True)
    reference_url = Column(String(1000), nullable=True)
    cve_id = Column(String(50), nullable=True)

    # Ingestion metadata
    content_hash = Column(String(64), nullable=True, index=True)  # SHA-256 for dedup
    ingestion_time = Column(DateTime(timezone=True), server_default=func.now())
    dataset_version = Column(String(100), nullable=True)

    chunks = relationship("KnowledgeChunk", back_populates="document", cascade="all, delete-orphan")

    __table_args__ = (
        Index("ix_knowledge_documents_source", "source"),
        Index("ix_knowledge_documents_technology", "technology"),
    )


class KnowledgeChunk(Base):
    """
    A text chunk from a knowledge document, with its vector stored in FAISS.
    Paper: "text chunking technology to disassemble each vulnerability example into independent text units"
    """
    __tablename__ = "knowledge_chunks"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    document_id = Column(String(36), ForeignKey("knowledge_documents.id"), nullable=False)

    # Text content
    chunk_text = Column(Text, nullable=False)
    chunk_position = Column(Integer, nullable=False)    # Position in parent document
    chunk_size = Column(Integer, nullable=True)         # Token count

    # FAISS mapping — CRITICAL for traceability
    # faiss_index_id maps to the row in the FAISS index
    faiss_index_id = Column(Integer, nullable=True, index=True)
    faiss_index_version = Column(String(100), nullable=True)
    embedding_model = Column(String(255), nullable=True)

    metadata_ = Column("metadata", JSON, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    document = relationship("KnowledgeDocument", back_populates="chunks")

    __table_args__ = (
        Index("ix_knowledge_chunks_faiss_id", "faiss_index_id"),
        Index("ix_knowledge_chunks_document", "document_id"),
    )


# ==============================================================================
# RAG Pipeline
# ==============================================================================

class Retrieval(Base):
    """
    Records one RAG retrieval operation — CRITICAL for auditability.
    Paper: the system must be traceable.
    """
    __tablename__ = "retrievals"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    scan_id = Column(String(36), ForeignKey("scans.id"), nullable=False)
    fingerprint_id = Column(String(36), ForeignKey("fingerprints.id"), nullable=False)

    # Query information
    query_text = Column(Text, nullable=False)
    query_embedding_model = Column(String(255), nullable=False)
    query_embedding_model_version = Column(String(100), nullable=True)

    # Retrieval parameters
    faiss_index_version = Column(String(100), nullable=True)
    top_k = Column(Integer, nullable=False)
    similarity_threshold = Column(Float, nullable=False)  # Paper: 0.6

    # Results
    results = Column(JSON, nullable=False)          # List of {chunk_id, score, text, source}
    max_similarity = Column(Float, nullable=True)   # Highest similarity found
    threshold_passed = Column(Boolean, nullable=False)  # True if max_sim >= threshold

    # Selected evidence for LLM
    selected_chunk_ids = Column(JSON, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    scan = relationship("Scan", back_populates="retrievals")
    fingerprint = relationship("Fingerprint", back_populates="retrievals")


class Analysis(Base):
    """
    LLM analysis result.
    Paper: LLM output includes vulnerability analysis, severity, remediation.
    """
    __tablename__ = "analyses"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    scan_id = Column(String(36), ForeignKey("scans.id"), nullable=False)
    retrieval_id = Column(String(36), ForeignKey("retrievals.id"), nullable=True)

    # LLM configuration used
    llm_provider = Column(String(100), nullable=False)
    llm_model = Column(String(255), nullable=False)
    prompt_version = Column(String(50), nullable=False)

    # Input/Output
    prompt_text = Column(Text, nullable=False)          # Full prompt sent to LLM
    raw_llm_response = Column(Text, nullable=False)     # Raw LLM response (for audit)

    # Parsed output (from paper's described output)
    potential_vulnerability = Column(Text, nullable=True)
    category = Column(Enum(VulnerabilityCategory), default=VulnerabilityCategory.UNKNOWN)
    affected_technology = Column(String(500), nullable=True)
    evidence_summary = Column(JSON, nullable=True)
    analysis_text = Column(Text, nullable=True)
    severity = Column(Enum(SeverityLevel), nullable=True)
    remediation_steps = Column(JSON, nullable=True)
    uncertainty_statement = Column(Text, nullable=True)
    validation_required = Column(Boolean, default=True)

    # Always INFERRED — never auto-confirmed
    evidence_type = Column(Enum(EvidenceType), default=EvidenceType.INFERRED)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    scan = relationship("Scan", back_populates="analyses")
    findings = relationship("Finding", back_populates="analysis", cascade="all, delete-orphan")


class Finding(Base):
    """
    A potential vulnerability finding requiring human validation.
    Paper: system operates as human-in-the-loop assistant.
    """
    __tablename__ = "findings"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    scan_id = Column(String(36), ForeignKey("scans.id"), nullable=False)
    analysis_id = Column(String(36), ForeignKey("analyses.id"), nullable=False)

    # Finding details
    title = Column(String(500), nullable=False)
    category = Column(Enum(VulnerabilityCategory), default=VulnerabilityCategory.UNKNOWN)
    severity = Column(Enum(SeverityLevel), nullable=True)
    description = Column(Text, nullable=True)
    affected_components = Column(JSON, nullable=True)
    remediation = Column(JSON, nullable=True)

    # Human validation status — starts as POTENTIAL
    status = Column(Enum(FindingStatus), default=FindingStatus.POTENTIAL, nullable=False, index=True)
    evidence_type = Column(Enum(EvidenceType), default=EvidenceType.INFERRED)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    scan = relationship("Scan", back_populates="findings")
    analysis = relationship("Analysis", back_populates="findings")
    validations = relationship("Validation", back_populates="finding", cascade="all, delete-orphan")

    __table_args__ = (
        Index("ix_findings_scan_status", "scan_id", "status"),
    )


class Validation(Base):
    """
    Human validation record for a finding.
    Paper: "human-in-the-loop assistant"
    """
    __tablename__ = "validations"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    finding_id = Column(String(36), ForeignKey("findings.id"), nullable=False)

    # Reviewer information
    reviewer = Column(String(255), nullable=False)
    review_timestamp = Column(DateTime(timezone=True), server_default=func.now())

    # Status transition
    old_status = Column(Enum(FindingStatus), nullable=False)
    new_status = Column(Enum(FindingStatus), nullable=False)
    comment = Column(Text, nullable=True)

    # Additional evidence requested
    additional_evidence_requested = Column(Text, nullable=True)

    finding = relationship("Finding", back_populates="validations")


class Report(Base):
    """Generated security report."""
    __tablename__ = "reports"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    scan_id = Column(String(36), ForeignKey("scans.id"), nullable=False)

    title = Column(String(500), nullable=False)
    format = Column(String(50), default="json")  # json | markdown | html
    content = Column(Text, nullable=False)
    file_path = Column(String(1000), nullable=True)

    # Summary statistics
    total_findings = Column(Integer, default=0)
    validated_findings = Column(Integer, default=0)
    rejected_findings = Column(Integer, default=0)
    pending_findings = Column(Integer, default=0)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    scan = relationship("Scan", back_populates="reports")


class AuditEvent(Base):
    """
    Immutable audit log for all system events.
    Paper: "the entire analytical chain is clear and transparent."
    """
    __tablename__ = "audit_events"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    event_type = Column(String(100), nullable=False, index=True)
    entity_type = Column(String(100), nullable=True)    # scan, finding, validation, etc.
    entity_id = Column(String(36), nullable=True, index=True)
    actor = Column(String(255), nullable=True)
    description = Column(Text, nullable=True)
    data = Column(JSON, nullable=True)
    timestamp = Column(DateTime(timezone=True), server_default=func.now(), index=True)

    __table_args__ = (
        Index("ix_audit_events_timestamp", "timestamp"),
    )


class User(Base):
    """
    User account model for administrative authentication.
    """
    __tablename__ = "users"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    email = Column(String(255), unique=True, nullable=False, index=True)
    hashed_password = Column(String(255), nullable=False)
    role = Column(String(50), default="admin", nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
